services:
  dev:
    container_name: valettesoftware
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ../app:/home/vscode/app
    userns_mode: keep-id:uid=1000,gid=1000
    ports:
      - "8080:8080"
      - "2205:22"
    networks:
      - valettesoftwarenetwork

networks:
  valettesoftwarenetwork:
    driver: bridge
