services:
  dev:
    container_name: valettecomputing
    build:
      context: .
      dockerfile: .Dockerfile
    #command: tail -f /dev/null
    volumes:
      - ../app:/usr/src/app
    ports:
      - 8080:80
      - 225:22
