name: tests
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    container: docker.io/library/golang:tip-trixie
    steps:
      - uses: actions/checkout@v5
      - name: build
        run: go build ./src/cmd/valettesoftware.go
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: valettesoftware
          path: ./valettesoftware

